import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../app/componets/Navbar'
import Sidebar from "./componets/Sidebar";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Movie Search App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="md:grid grid-cols-1 sm:grid-cols-[250px,1fr]  mt-3 ml-3">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
